# Generated by Django 5.2.4 on 2025-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTOPProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='Product Name')),
                ('local_admin', models.CharField(max_length=200, verbose_name='Local Administration')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('shop_name', models.CharField(max_length=500, verbose_name='Shop Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OTOP Product',
                'verbose_name_plural': 'OTOP Products',
                'ordering': ['province', 'district', 'product_name'],
            },
        ),
    ]
